apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders
  namespace: istio-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
        version: v1
    spec:
      containers:
        - args:
            - -listen=:8080
            - -text=Hello from ORDERS v1
          image: hashicorp/http-echo:1.0
          name: orders
          ports:
            - containerPort: 8080
