apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments
  namespace: istio-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
        version: v1
    spec:
      containers:
        - args:
            - -listen=:8080
            - -text=Hello from PAYMENTS v1
          image: hashicorp/http-echo:1.0
          name: payments
          ports:
            - containerPort: 8080
