name: CI

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

env:
  MISE_NO_ENV: "1"

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803
        with:
          persist-credentials: false
      - uses: jdx/mise-action@5228313ee0372e111a38da051671ca30fc5a96db
      - run: mise exec -- pre-commit run --all-files
